### ISSUE TITLE
Error "SyntaxError: Unexpected end of JSON input","    at JSON.parse (<anonymous>

### ISSUE THREAD

**Issue by akayalml** [maxsagt/lambda-openai-stream#1]
The local testing failing with following error.
`
START RequestId: 6c1ff0fa-f8e6-403a-933f-1e0eb2eb7e08 Version: $LATEST
2023-08-10T10:52:02.324Z        6c1ff0fa-f8e6-403a-933f-1e0eb2eb7e08    ERROR   Error parsing line: {"id":"chatcmpl-xxxxx","object":"chat.completion.chunk","created":1691664722,"model":"gpt-3.5-turbo-0613","choices":[{"index":0,"delta":{"content":"umn"},"finish_reas    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1180:26))rror in streamOpenAIResponse: SyntaxError: Unexpected end of JSON input
2023-08-10T10:52:02.375Z        6c1ff0fa-f8e6-403a-933f-1e0eb2eb7e08    ERROR   Invoke Error    {"errorType":"SyntaxError","errorMessage":"Unexpected end of JSON input","stack":["SyntaxError: Unexpected end of JSON input","    at JSON.parse (<anonymous>)","    at file:///var/task/streamOpenAIResponse.mjs:40:29","    at Array.map (<anonymous>)","    at processChunk (file:///var/task/streamOpenAIResponse.mjs:38:10)","    at streamOpenAIResponse (file:///var/task/streamOpenAIResponse.mjs:58:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Runtime.handler (file:///var/task/index.mjs:22:19)","    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1180:26)"]}
END RequestId: 6c1ff0fa-f8e6-403a-933f-1e0eb2eb7e08
REPORT RequestId: 6c1ff0fa-f8e6-403a-933f-1e0eb2eb7e08  Init Duration: 1.79 ms  Duration: 6378.76 ms    Billed Duration: 6379 ms        Memory Size: 512 MB     Max Memory Used: 512 MB
{"statusCode":200,"headers":{"Content-Type":"application/json"}}
Request started.
`

**Comment by maxsagt** [comment]
Streaming will be officially supported in V4 of the OpenAI Node library. It is currently in Beta, but I can recommend switching already. Would that work for you?
-> https://github.com/openai/openai-node/discussions/182

**Comment by maxsagt** [comment]
Hi! Streaming is now officially supported by OpenAI: https://github.com/openai/openai-node
